server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  ai:
    model:
      chat: ollama
      embedding: ollama

    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2
      embedding:
        options:
          model: mxbai-embed-large

    vectorstore:
      chroma:
        client:
          host: http://localhost
          port: 8000
        collection-name: my_collection
        initialize-schema: true